/*
 * generated by Xtext
 */
package com.github.funthomas424242.language;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class RezeptRuntimeModule extends com.github.funthomas424242.language.AbstractRezeptRuntimeModule {

}
