/*
 * generated by Xtext
 */
package com.github.funthomas424242.language;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class RezeptStandaloneSetup extends RezeptStandaloneSetupGenerated{

	public static void doSetup() {
		new RezeptStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

