/*
 * generated by Xtext
 */
package com.github.funthomas424242.language.ui.contentassist

import com.github.funthomas424242.language.ui.contentassist.AbstractRezeptProposalProvider

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
class RezeptProposalProvider extends AbstractRezeptProposalProvider {
}
