/*
 * generated by Xtext
 */
package com.github.funthomas424242.language.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class RezeptUiModule extends com.github.funthomas424242.language.ui.AbstractRezeptUiModule {
	public RezeptUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
