/*
 * generated by Xtext 2.9.2
 */
package com.github.funthomas424242.dsl


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class RezeptRuntimeModule extends AbstractRezeptRuntimeModule {
}
