/*
 * generated by Xtext 2.9.2
 */
package com.github.funthomas424242.dsl


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class RezeptStandaloneSetup extends RezeptStandaloneSetupGenerated {

	def static void doSetup() {
		new RezeptStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
